<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, '`');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{ \"messaging_product\": \"whatsapp\", \"to\": \"918697853766\", \"type\": \"template\", \"template\": { \"name\": \"hello_world\", \"language\": { \"code\": \"en_US\" } } }");

$headers = array();
$headers[] = 'Authorization: Bearer EAAF04t7lPe4BAFJznZBJKviRpl1HeLKNWEtL9Hx72ZBSQp01CBskcqkihbhKBM3ThSYsirEslZAfBDBdb6Gjn0hHmeZASoFdom4eD1Yp9sP7pVy19rkMCQkalZA7tX9MVWvtCzFKda3a9UajyYTv8YoZALP9jasakpXCvh7KpUSXzjfuFY5IyQ6pZBuwq93MlVkh8l7mEDrWgZDZD';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo $result;


?>