name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2021-08-12
version: '9.2.4'
project: 'drupal'
datestamp: 1628791240
